### ISSUE TITLE
Error "The <SignUp/> and <SignIn/> components cannot render when a user is already signed in"

### ISSUE THREAD

**Issue by Enalmada** [clerkinc/clerk-next-app-router-starter#4]
I just installed clerk in my next.js 13.4.7 app router application following the documentation as close as possible with a fresh clerk account with default settings.  When running it, the sign-in button triggers the login flow but after it returns, I see my user image icon but I can't hit any protected routes.  This error shows up in the console when I try: 
```
🔒 Clerk:
The <SignUp/> and <SignIn/> components cannot render when a user is already signed in, unless the application allows multiple sessions. Since a user is signed in and this application only allows a single session, Clerk is redirecting to the Home URL instead.
(This notice only appears in development)
```

I checked out this `clerk-next-app-router-starter` to see if I could use it to figure out what was wrong with my project and I am getting the same error when trying to do the sign up and API request example buttons.   
console says after going through login flow `http://localhost:3000/api/getAuthenticatedUserId 401 (Unauthorized)`

I then updated all dependencies to the latest just to make sure it wasn't a solved problem but no luck. 
```
 "@clerk/nextjs": "^4.21.13",
 "next": "13.4.7"
```

I do have chrome debugger with network and console set to "preserve log" (and disable cache) so I can see errors before redirection.  I believe this error may be missed without preserve log.

Any ideas why a default clerk account and clerk-next-app-router-starter would have this kind of trouble out of the box?

update: I am now seeing this CORS in the logs 
```
localhost/:1 Access to fetch at 'https://xxx.accounts.dev/sign-in?redirect_url=http%3A%2F%2Flocalhost%3A3000%2Fsign-in#__clerk_db_jwt....]' (redirected from 'http://localhost:3000/sign-in') from origin 'http://localhost:3000/' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

I am using a very new Clerk.  Is it possible that  Development origin URL "auto" is broken?  This page Clerk > Paths  says "Clerk automatically detects the development origin in your local environment (e.g. http://localhost:3000/)" but perhaps Clerk or the sample app need to be setting cors headers?
Perhaps the author of repo is using Clerk env that has some settings that are different from what a user would have after just creating account and following new user directions?

**Comment by codinginflow** [comment]
Same problem here. I don't see the CORS message in the logs but I get redirected to the (non-authenticated) front page even though I'm logged in. I get the same error message. Sometimes it lets me go through but then it usually redirects again after refreshing the page.

Edit: My error went away and also didn't happen in production. No idea what caused it but it must've been related to my localhost server.

**Comment by jlil** [comment]
@perkinsjr any chance you can look into this urgently? it's blocking our deployment to prod. Thanks

**Comment by perkinsjr** [comment]
@jlil Can you open a support request either in the Discord or support@clerk.com.

This seems unrelated to the template and needs actual support if it's blocking production.

**Comment by LekoArts** [comment]
Closing this issue as this should be handled through support if you're seeing something like this. It's unrelated to this template.
